### ISSUE TITLE
Always getting Authentication Error

### ISSUE THREAD

**Issue by nisar6063** [masumsoft/cassandra-exporter#3]
I tried this by giving username/password. doesn't work

RINMAC232:cassandra-exporter-macos$ HOST=127.0.0.1 KEYSPACE=abc USERNAME=cassandra PASSWORD=cassandra TABLE=my_table ./export
{ [Error: All host(s) tried for query failed. First host tried, 127.0.0.1:9042: AuthenticationError: Username and/or password are incorrect. See innerErrors.]
  innerErrors: 
   { '127.0.0.1:9042': 
      { Error: Username and/or password are incorrect
          at AuthenticationError.DriverError (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/errors.js:14:19)
          at new AuthenticationError (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/errors.js:80:30)
          at authResponseCallback (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/connection.js:321:25)
          at Connection.invokeCallback (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/connection.js:602:5)
          at Connection.handleResult (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/connection.js:540:8)
          at emitThree (events.js:116:13)
          at ResultEmitter.emit (events.js:194:7)
          at ResultEmitter.each (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/streams.js:500:17)
          at ResultEmitter._write (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/streams.js:484:10)
          at doWrite (_stream_writable.js:334:12)
          at writeOrBuffer (_stream_writable.js:320:5)
          at ResultEmitter.Writable.write (_stream_writable.js:247:11)
          at Parser.ondata (_stream_readable.js:555:20)
          at emitOne (events.js:96:13)
          at Parser.emit (events.js:188:7)
          at readableAddChunk (_stream_readable.js:176:18)
        name: 'AuthenticationError',
        stack: 'Error: Username and/or password are incorrect\n    at AuthenticationError.DriverError (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/errors.js:14:19)\n    at new AuthenticationError (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/errors.js:80:30)\n    at authResponseCallback (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/connection.js:321:25)\n    at Connection.invokeCallback (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/connection.js:602:5)\n    at Connection.handleResult (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/connection.js:540:8)\n    at emitThree (events.js:116:13)\n    at ResultEmitter.emit (events.js:194:7)\n    at ResultEmitter.each (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/streams.js:500:17)\n    at ResultEmitter._write (/snapshot/Users/masum/Projects/Nodesty/cassandra-exporter/node_modules/cassandra-driver/lib/streams.js:484:10)\n    at doWrite (_stream_writable.js:334:12)\n    at writeOrBuffer (_stream_writable.js:320:5)\n    at ResultEmitter.Writable.write (_stream_writable.js:247:11)\n    at Parser.ondata (_stream_readable.js:555:20)\n    at emitOne (events.js:96:13)\n    at Parser.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)',
        message: 'Username and/or password are incorrect',
        info: 'Represents an authentication error from the driver or from a Cassandra node.',
        additionalInfo: [Object] } },
  info: 'Represents an error when a query cannot be performed because no host is available or could be reached by the driver.',
  message: 'All host(s) tried for query failed. First host tried, 127.0.0.1:9042: AuthenticationError: Username and/or password are incorrect. See innerErrors.' }
RINMAC232:cassandra-exporter-macos$

**Comment by masumsoft** [comment]
Please use USER instead of USERNAME, the readme contained a misleading typo there, fixed now.
